/**
 * Every UAE sub-service page's own images, one entry per page.
 *
 * THE THIRTY-THREE PAGES SHARE ONE TEMPLATE BUT NEVER AN IMAGE (client
 * instruction, 20260913). buildSubs() reads a page's entry here for its hero,
 * brief panel, why-us banner, success story, band, the six strip panels and the
 * closing section; nothing falls back to a sibling's photograph. To change one
 * page's picture, replace the file this names (or point the entry elsewhere).
 * Paths are under public/assets/content/uploads/. The insights cards are not
 * listed: they carry the site's articles' own images.
 */
/* Self-contained on purpose: subTypes imports this file, so this file imports
   nothing back from it. */
type SubImage = string | string[];

export interface SubPageImages {
  hero: SubImage;
  panel: SubImage;
  why: SubImage;
  story: SubImage;
  band: SubImage;
  /** The six strip panels, in order. */
  strip: SubImage[];
  talk: SubImage;
}

/** Keyed by `<service slug>/<page slug>`. */
export const SUB_PAGE_IMAGES: Record<string, SubPageImages> = {
  'accounting-tax-services/accounting-bookkeeping': {
    hero: 'services/sub/accounting-tax-services/accounting-bookkeeping-hero.webp',
    panel: 'services/sub/accounting-tax-services/accounting-bookkeeping-panel.webp',
    why: 'services/sub/accounting-tax-services/accounting-bookkeeping-why.webp',
    story: 'services/sub/accounting-tax-services/accounting-bookkeeping-story.webp',
    band: 'services/sub/accounting-tax-services/accounting-bookkeeping-band.webp',
    strip: [
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-1.webp',
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-2.webp',
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-3.webp',
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-4.webp',
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-5.webp',
      'services/sub/accounting-tax-services/accounting-bookkeeping-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/accounting-bookkeeping-talk.webp',
  },
  'accounting-tax-services/cfo-services': {
    hero: 'services/sub/accounting-tax-services/cfo-services-hero.webp',
    panel: 'services/sub/accounting-tax-services/cfo-services-panel.webp',
    why: 'services/sub/accounting-tax-services/cfo-services-why.webp',
    story: 'services/sub/accounting-tax-services/cfo-services-story.webp',
    band: 'services/sub/accounting-tax-services/cfo-services-band.webp',
    strip: [
      'services/sub/accounting-tax-services/cfo-services-strip-1.webp',
      'services/sub/accounting-tax-services/cfo-services-strip-2.webp',
      'services/sub/accounting-tax-services/cfo-services-strip-3.webp',
      'services/sub/accounting-tax-services/cfo-services-strip-4.webp',
      'services/sub/accounting-tax-services/cfo-services-strip-5.webp',
      'services/sub/accounting-tax-services/cfo-services-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/cfo-services-talk.webp',
  },
  'accounting-tax-services/management-reporting': {
    hero: 'services/sub/accounting-tax-services/management-reporting-hero.webp',
    panel: 'services/sub/accounting-tax-services/management-reporting-panel.webp',
    why: 'services/sub/accounting-tax-services/management-reporting-why.webp',
    story: 'services/sub/accounting-tax-services/management-reporting-story.webp',
    band: 'services/sub/accounting-tax-services/management-reporting-band.webp',
    strip: [
      'services/sub/accounting-tax-services/management-reporting-strip-1.webp',
      'services/sub/accounting-tax-services/management-reporting-strip-2.webp',
      'services/sub/accounting-tax-services/management-reporting-strip-3.webp',
      'services/sub/accounting-tax-services/management-reporting-strip-4.webp',
      'services/sub/accounting-tax-services/management-reporting-strip-5.webp',
      'services/sub/accounting-tax-services/management-reporting-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/management-reporting-talk.webp',
  },
  'accounting-tax-services/budgeting-forecasting': {
    hero: 'services/sub/accounting-tax-services/budgeting-forecasting-hero.webp',
    panel: 'services/sub/accounting-tax-services/budgeting-forecasting-panel.webp',
    why: 'services/sub/accounting-tax-services/budgeting-forecasting-why.webp',
    story: 'services/sub/accounting-tax-services/budgeting-forecasting-story.webp',
    band: 'services/sub/accounting-tax-services/budgeting-forecasting-band.webp',
    strip: [
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-1.webp',
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-2.webp',
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-3.webp',
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-4.webp',
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-5.webp',
      'services/sub/accounting-tax-services/budgeting-forecasting-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/budgeting-forecasting-talk.webp',
  },
  'accounting-tax-services/financial-reporting': {
    hero: 'services/sub/accounting-tax-services/financial-reporting-hero.webp',
    panel: 'services/sub/accounting-tax-services/financial-reporting-panel.webp',
    why: 'services/sub/accounting-tax-services/financial-reporting-why.webp',
    story: 'services/sub/accounting-tax-services/financial-reporting-story.webp',
    band: 'services/sub/accounting-tax-services/financial-reporting-band.webp',
    strip: [
      'services/sub/accounting-tax-services/financial-reporting-strip-1.webp',
      'services/sub/accounting-tax-services/financial-reporting-strip-2.webp',
      'services/sub/accounting-tax-services/financial-reporting-strip-3.webp',
      'services/sub/accounting-tax-services/financial-reporting-strip-4.webp',
      'services/sub/accounting-tax-services/financial-reporting-strip-5.webp',
      'services/sub/accounting-tax-services/financial-reporting-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/financial-reporting-talk.webp',
  },
  'accounting-tax-services/external-audit-support': {
    hero: 'services/sub/accounting-tax-services/external-audit-support-hero.webp',
    panel: 'services/sub/accounting-tax-services/external-audit-support-panel.webp',
    why: 'services/sub/accounting-tax-services/external-audit-support-why.webp',
    story: 'services/sub/accounting-tax-services/external-audit-support-story.webp',
    band: 'services/sub/accounting-tax-services/external-audit-support-band.webp',
    strip: [
      'services/sub/accounting-tax-services/external-audit-support-strip-1.webp',
      'services/sub/accounting-tax-services/external-audit-support-strip-2.webp',
      'services/sub/accounting-tax-services/external-audit-support-strip-3.webp',
      'services/sub/accounting-tax-services/external-audit-support-strip-4.webp',
      'services/sub/accounting-tax-services/external-audit-support-strip-5.webp',
      'services/sub/accounting-tax-services/external-audit-support-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/external-audit-support-talk.webp',
  },
  'accounting-tax-services/corporate-tax-services': {
    hero: 'services/sub/accounting-tax-services/corporate-tax-services-hero.webp',
    panel: 'services/sub/accounting-tax-services/corporate-tax-services-panel.webp',
    why: 'services/sub/accounting-tax-services/corporate-tax-services-why.webp',
    story: 'services/sub/accounting-tax-services/corporate-tax-services-story.webp',
    band: 'services/sub/accounting-tax-services/corporate-tax-services-band.webp',
    strip: [
      'services/sub/accounting-tax-services/corporate-tax-services-strip-1.webp',
      'services/sub/accounting-tax-services/corporate-tax-services-strip-2.webp',
      'services/sub/accounting-tax-services/corporate-tax-services-strip-3.webp',
      'services/sub/accounting-tax-services/corporate-tax-services-strip-4.webp',
      'services/sub/accounting-tax-services/corporate-tax-services-strip-5.webp',
      'services/sub/accounting-tax-services/corporate-tax-services-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/corporate-tax-services-talk.webp',
  },
  'accounting-tax-services/vat-services': {
    hero: 'services/sub/accounting-tax-services/vat-services-hero.webp',
    panel: 'services/sub/accounting-tax-services/vat-services-panel.webp',
    why: 'services/sub/accounting-tax-services/vat-services-why.webp',
    story: 'services/sub/accounting-tax-services/vat-services-story.webp',
    band: 'services/sub/accounting-tax-services/vat-services-band.webp',
    strip: [
      'services/sub/accounting-tax-services/vat-services-strip-1.webp',
      'services/sub/accounting-tax-services/vat-services-strip-2.webp',
      'services/sub/accounting-tax-services/vat-services-strip-3.webp',
      'services/sub/accounting-tax-services/vat-services-strip-4.webp',
      'services/sub/accounting-tax-services/vat-services-strip-5.webp',
      'services/sub/accounting-tax-services/vat-services-strip-6.webp',
    ],
    talk: 'services/sub/accounting-tax-services/vat-services-talk.webp',
  },
  'real-estate-transactions/buy-property': {
    hero: 'services/sub/real-estate-transactions/buy-property-hero.webp',
    panel: 'services/sub/real-estate-transactions/buy-property-panel.webp',
    why: 'services/sub/real-estate-transactions/buy-property-why.webp',
    story: 'services/sub/real-estate-transactions/buy-property-story.webp',
    band: 'services/sub/real-estate-transactions/buy-property-band.webp',
    strip: [
      'services/sub/real-estate-transactions/buy-property-strip-1.webp',
      'services/sub/real-estate-transactions/buy-property-strip-2.webp',
      'services/sub/real-estate-transactions/buy-property-strip-3.webp',
      'services/sub/real-estate-transactions/buy-property-strip-4.webp',
      'services/sub/real-estate-transactions/buy-property-strip-5.webp',
      'services/sub/real-estate-transactions/buy-property-strip-6.webp',
    ],
    talk: 'services/sub/real-estate-transactions/buy-property-talk.webp',
  },
  'real-estate-transactions/sell-rent-lease-property': {
    hero: 'services/sub/real-estate-transactions/sell-rent-lease-property-hero.webp',
    panel: 'services/sub/real-estate-transactions/sell-rent-lease-property-panel.webp',
    why: 'services/sub/real-estate-transactions/sell-rent-lease-property-why.webp',
    story: 'services/sub/real-estate-transactions/sell-rent-lease-property-story.webp',
    band: 'services/sub/real-estate-transactions/sell-rent-lease-property-band.webp',
    strip: [
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-1.webp',
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-2.webp',
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-3.webp',
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-4.webp',
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-5.webp',
      'services/sub/real-estate-transactions/sell-rent-lease-property-strip-6.webp',
    ],
    talk: 'services/sub/real-estate-transactions/sell-rent-lease-property-talk.webp',
  },
  'real-estate-transactions/off-plan-properties': {
    hero: 'services/sub/real-estate-transactions/off-plan-properties-hero.webp',
    panel: 'services/sub/real-estate-transactions/off-plan-properties-panel.webp',
    why: 'services/sub/real-estate-transactions/off-plan-properties-why.webp',
    story: 'services/sub/real-estate-transactions/off-plan-properties-story.webp',
    band: 'services/sub/real-estate-transactions/off-plan-properties-band.webp',
    strip: [
      'services/sub/real-estate-transactions/off-plan-properties-strip-1.webp',
      'services/sub/real-estate-transactions/off-plan-properties-strip-2.webp',
      'services/sub/real-estate-transactions/off-plan-properties-strip-3.webp',
      'services/sub/real-estate-transactions/off-plan-properties-strip-4.webp',
      'services/sub/real-estate-transactions/off-plan-properties-strip-5.webp',
      'services/sub/real-estate-transactions/off-plan-properties-strip-6.webp',
    ],
    talk: 'services/sub/real-estate-transactions/off-plan-properties-talk.webp',
  },
  'mortgages-services/residential-mortgages': {
    hero: 'services/sub/mortgages-services/residential-mortgages-hero.webp',
    panel: 'services/sub/mortgages-services/residential-mortgages-panel.webp',
    why: 'services/sub/mortgages-services/residential-mortgages-why.webp',
    story: 'services/sub/mortgages-services/residential-mortgages-story.webp',
    band: 'services/sub/mortgages-services/residential-mortgages-band.webp',
    strip: [
      'services/sub/mortgages-services/residential-mortgages-strip-1.webp',
      'services/sub/mortgages-services/residential-mortgages-strip-2.webp',
      'services/sub/mortgages-services/residential-mortgages-strip-3.webp',
      'services/sub/mortgages-services/residential-mortgages-strip-4.webp',
      'services/sub/mortgages-services/residential-mortgages-strip-5.webp',
      'services/sub/mortgages-services/residential-mortgages-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/residential-mortgages-talk.webp',
  },
  'mortgages-services/commercial-mortgages': {
    hero: 'services/sub/mortgages-services/commercial-mortgages-hero.webp',
    panel: 'services/sub/mortgages-services/commercial-mortgages-panel.webp',
    why: 'services/sub/mortgages-services/commercial-mortgages-why.webp',
    story: 'services/sub/mortgages-services/commercial-mortgages-story.webp',
    band: 'services/sub/mortgages-services/commercial-mortgages-band.webp',
    strip: [
      'services/sub/mortgages-services/commercial-mortgages-strip-1.webp',
      'services/sub/mortgages-services/commercial-mortgages-strip-2.webp',
      'services/sub/mortgages-services/commercial-mortgages-strip-3.webp',
      'services/sub/mortgages-services/commercial-mortgages-strip-4.webp',
      'services/sub/mortgages-services/commercial-mortgages-strip-5.webp',
      'services/sub/mortgages-services/commercial-mortgages-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/commercial-mortgages-talk.webp',
  },
  'mortgages-services/mortgage-pre-approval': {
    hero: 'services/sub/mortgages-services/mortgage-pre-approval-hero.webp',
    panel: 'services/sub/mortgages-services/mortgage-pre-approval-panel.webp',
    why: 'services/sub/mortgages-services/mortgage-pre-approval-why.webp',
    story: 'services/sub/mortgages-services/mortgage-pre-approval-story.webp',
    band: 'services/sub/mortgages-services/mortgage-pre-approval-band.webp',
    strip: [
      'services/sub/mortgages-services/mortgage-pre-approval-strip-1.webp',
      'services/sub/mortgages-services/mortgage-pre-approval-strip-2.webp',
      'services/sub/mortgages-services/mortgage-pre-approval-strip-3.webp',
      'services/sub/mortgages-services/mortgage-pre-approval-strip-4.webp',
      'services/sub/mortgages-services/mortgage-pre-approval-strip-5.webp',
      'services/sub/mortgages-services/mortgage-pre-approval-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/mortgage-pre-approval-talk.webp',
  },
  'mortgages-services/refinancing': {
    hero: 'services/sub/mortgages-services/refinancing-hero.webp',
    panel: 'services/sub/mortgages-services/refinancing-panel.webp',
    why: 'services/sub/mortgages-services/refinancing-why.webp',
    story: 'services/sub/mortgages-services/refinancing-story.webp',
    band: 'services/sub/mortgages-services/refinancing-band.webp',
    strip: [
      'services/sub/mortgages-services/refinancing-strip-1.webp',
      'services/sub/mortgages-services/refinancing-strip-2.webp',
      'services/sub/mortgages-services/refinancing-strip-3.webp',
      'services/sub/mortgages-services/refinancing-strip-4.webp',
      'services/sub/mortgages-services/refinancing-strip-5.webp',
      'services/sub/mortgages-services/refinancing-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/refinancing-talk.webp',
  },
  'mortgages-services/non-resident-mortgages': {
    hero: 'services/sub/mortgages-services/non-resident-mortgages-hero.webp',
    panel: 'services/sub/mortgages-services/non-resident-mortgages-panel.webp',
    why: 'services/sub/mortgages-services/non-resident-mortgages-why.webp',
    story: 'services/sub/mortgages-services/non-resident-mortgages-story.webp',
    band: 'services/sub/mortgages-services/non-resident-mortgages-band.webp',
    strip: [
      'services/sub/mortgages-services/non-resident-mortgages-strip-1.webp',
      'services/sub/mortgages-services/non-resident-mortgages-strip-2.webp',
      'services/sub/mortgages-services/non-resident-mortgages-strip-3.webp',
      'services/sub/mortgages-services/non-resident-mortgages-strip-4.webp',
      'services/sub/mortgages-services/non-resident-mortgages-strip-5.webp',
      'services/sub/mortgages-services/non-resident-mortgages-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/non-resident-mortgages-talk.webp',
  },
  'mortgages-services/islamic-finance': {
    hero: 'services/sub/mortgages-services/islamic-finance-hero.webp',
    panel: 'services/sub/mortgages-services/islamic-finance-panel.webp',
    why: 'services/sub/mortgages-services/islamic-finance-why.webp',
    story: 'services/sub/mortgages-services/islamic-finance-story.webp',
    band: 'services/sub/mortgages-services/islamic-finance-band.webp',
    strip: [
      'services/sub/mortgages-services/islamic-finance-strip-1.webp',
      'services/sub/mortgages-services/islamic-finance-strip-2.webp',
      'services/sub/mortgages-services/islamic-finance-strip-3.webp',
      'services/sub/mortgages-services/islamic-finance-strip-4.webp',
      'services/sub/mortgages-services/islamic-finance-strip-5.webp',
      'services/sub/mortgages-services/islamic-finance-strip-6.webp',
    ],
    talk: 'services/sub/mortgages-services/islamic-finance-talk.webp',
  },
  'valuation-and-advisory/business-valuation': {
    hero: 'services/sub/valuation-and-advisory/business-valuation-hero.webp',
    panel: 'services/sub/valuation-and-advisory/business-valuation-panel.webp',
    why: 'services/sub/valuation-and-advisory/business-valuation-why.webp',
    story: 'services/sub/valuation-and-advisory/business-valuation-story.webp',
    band: 'services/sub/valuation-and-advisory/business-valuation-band.webp',
    strip: [
      'services/sub/valuation-and-advisory/business-valuation-strip-1.webp',
      'services/sub/valuation-and-advisory/business-valuation-strip-2.webp',
      'services/sub/valuation-and-advisory/business-valuation-strip-3.webp',
      'services/sub/valuation-and-advisory/business-valuation-strip-4.webp',
      'services/sub/valuation-and-advisory/business-valuation-strip-5.webp',
      'services/sub/valuation-and-advisory/business-valuation-strip-6.webp',
    ],
    talk: 'services/sub/valuation-and-advisory/business-valuation-talk.webp',
  },
  /* Property Valuation replaced Company Valuation here (20260916) and kept that
     page's files where the photograph suits property, renamed and with the strip
     re-ordered to the new list. Two did not: the hero (a bank district) is now
     the unused Abu Dhabi skyline, and strip 5 (a jet turbine) an unused farmland
     shot, both named where they already sit rather than copied. */
  'valuation-and-advisory/property-valuation': {
    hero: 'uae/home/answer-skyline.webp',
    panel: 'services/sub/valuation-and-advisory/property-valuation-panel.webp',
    why: 'services/sub/valuation-and-advisory/property-valuation-why.webp',
    story: 'services/sub/valuation-and-advisory/property-valuation-story.webp',
    band: 'services/sub/valuation-and-advisory/property-valuation-band.webp',
    strip: [
      'services/sub/valuation-and-advisory/property-valuation-strip-1.webp',
      'services/sub/valuation-and-advisory/property-valuation-strip-2.webp',
      'services/sub/valuation-and-advisory/property-valuation-strip-3.webp',
      'services/sub/valuation-and-advisory/property-valuation-strip-4.webp',
      '2025/04/pexels-googledeepmind-17483910-copy-1124x1536.jpg',
      'services/sub/valuation-and-advisory/property-valuation-strip-6.webp',
    ],
    talk: 'services/sub/valuation-and-advisory/property-valuation-talk.webp',
  },
  'valuation-and-advisory/plant-machinery-valuation': {
    hero: 'services/sub/valuation-and-advisory/plant-machinery-valuation-hero.webp',
    panel: 'services/sub/valuation-and-advisory/plant-machinery-valuation-panel.webp',
    why: 'services/sub/valuation-and-advisory/plant-machinery-valuation-why.webp',
    story: 'services/sub/valuation-and-advisory/plant-machinery-valuation-story.webp',
    band: 'services/sub/valuation-and-advisory/plant-machinery-valuation-band.webp',
    strip: [
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-1.webp',
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-2.webp',
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-3.webp',
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-4.webp',
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-5.webp',
      'services/sub/valuation-and-advisory/plant-machinery-valuation-strip-6.webp',
    ],
    talk: 'services/sub/valuation-and-advisory/plant-machinery-valuation-talk.webp',
  },
  'valuation-and-advisory/asset-valuation': {
    hero: 'services/sub/valuation-and-advisory/asset-valuation-hero.webp',
    panel: 'services/sub/valuation-and-advisory/asset-valuation-panel.webp',
    why: 'services/sub/valuation-and-advisory/asset-valuation-why.webp',
    story: 'services/sub/valuation-and-advisory/asset-valuation-story.webp',
    band: 'services/sub/valuation-and-advisory/asset-valuation-band.webp',
    strip: [
      'services/sub/valuation-and-advisory/asset-valuation-strip-1.webp',
      'services/sub/valuation-and-advisory/asset-valuation-strip-2.webp',
      'services/sub/valuation-and-advisory/asset-valuation-strip-3.webp',
      'services/sub/valuation-and-advisory/asset-valuation-strip-4.webp',
      'services/sub/valuation-and-advisory/asset-valuation-strip-5.webp',
      'services/sub/valuation-and-advisory/asset-valuation-strip-6.webp',
    ],
    talk: 'services/sub/valuation-and-advisory/asset-valuation-talk.webp',
  },
  'valuation-and-advisory/financial-valuation': {
    hero: 'services/sub/valuation-and-advisory/financial-valuation-hero.webp',
    panel: 'services/sub/valuation-and-advisory/financial-valuation-panel.webp',
    why: 'services/sub/valuation-and-advisory/financial-valuation-why.webp',
    story: 'services/sub/valuation-and-advisory/financial-valuation-story.webp',
    band: 'services/sub/valuation-and-advisory/financial-valuation-band.webp',
    strip: [
      'services/sub/valuation-and-advisory/financial-valuation-strip-1.webp',
      'services/sub/valuation-and-advisory/financial-valuation-strip-2.webp',
      'services/sub/valuation-and-advisory/financial-valuation-strip-3.webp',
      'services/sub/valuation-and-advisory/financial-valuation-strip-4.webp',
      'services/sub/valuation-and-advisory/financial-valuation-strip-5.webp',
      'services/sub/valuation-and-advisory/financial-valuation-strip-6.webp',
    ],
    talk: 'services/sub/valuation-and-advisory/financial-valuation-talk.webp',
  },
  'research-intelligence/real-estate-research': {
    hero: 'services/sub/research-intelligence/real-estate-research-hero.webp',
    panel: 'services/sub/research-intelligence/real-estate-research-panel.webp',
    why: 'services/sub/research-intelligence/real-estate-research-why.webp',
    story: 'services/sub/research-intelligence/real-estate-research-story.webp',
    band: 'services/sub/research-intelligence/real-estate-research-band.webp',
    strip: [
      'services/sub/research-intelligence/real-estate-research-strip-1.webp',
      'services/sub/research-intelligence/real-estate-research-strip-2.webp',
      'services/sub/research-intelligence/real-estate-research-strip-3.webp',
      'services/sub/research-intelligence/real-estate-research-strip-4.webp',
      'services/sub/research-intelligence/real-estate-research-strip-5.webp',
      'services/sub/research-intelligence/real-estate-research-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/real-estate-research-talk.webp',
  },
  'research-intelligence/market-research': {
    hero: 'services/sub/research-intelligence/market-research-hero.webp',
    panel: 'services/sub/research-intelligence/market-research-panel.webp',
    why: 'services/sub/research-intelligence/market-research-why.webp',
    story: 'services/sub/research-intelligence/market-research-story.webp',
    band: 'services/sub/research-intelligence/market-research-band.webp',
    strip: [
      'services/sub/research-intelligence/market-research-strip-1.webp',
      'services/sub/research-intelligence/market-research-strip-2.webp',
      'services/sub/research-intelligence/market-research-strip-3.webp',
      'services/sub/research-intelligence/market-research-strip-4.webp',
      'services/sub/research-intelligence/market-research-strip-5.webp',
      'services/sub/research-intelligence/market-research-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/market-research-talk.webp',
  },
  'research-intelligence/investment-research': {
    hero: 'services/sub/research-intelligence/investment-research-hero.webp',
    panel: 'services/sub/research-intelligence/investment-research-panel.webp',
    why: 'services/sub/research-intelligence/investment-research-why.webp',
    story: 'services/sub/research-intelligence/investment-research-story.webp',
    band: 'services/sub/research-intelligence/investment-research-band.webp',
    strip: [
      'services/sub/research-intelligence/investment-research-strip-1.webp',
      'services/sub/research-intelligence/investment-research-strip-2.webp',
      'services/sub/research-intelligence/investment-research-strip-3.webp',
      'services/sub/research-intelligence/investment-research-strip-4.webp',
      'services/sub/research-intelligence/investment-research-strip-5.webp',
      'services/sub/research-intelligence/investment-research-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/investment-research-talk.webp',
  },
  'research-intelligence/feasibility-studies': {
    hero: 'services/sub/research-intelligence/feasibility-studies-hero.webp',
    panel: 'services/sub/research-intelligence/feasibility-studies-panel.webp',
    why: 'services/sub/research-intelligence/feasibility-studies-why.webp',
    story: 'services/sub/research-intelligence/feasibility-studies-story.webp',
    band: 'services/sub/research-intelligence/feasibility-studies-band.webp',
    strip: [
      'services/sub/research-intelligence/feasibility-studies-strip-1.webp',
      'services/sub/research-intelligence/feasibility-studies-strip-2.webp',
      'services/sub/research-intelligence/feasibility-studies-strip-3.webp',
      'services/sub/research-intelligence/feasibility-studies-strip-4.webp',
      'services/sub/research-intelligence/feasibility-studies-strip-5.webp',
      'services/sub/research-intelligence/feasibility-studies-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/feasibility-studies-talk.webp',
  },
  'research-intelligence/market-intelligence': {
    hero: 'services/sub/research-intelligence/market-intelligence-hero.webp',
    panel: 'services/sub/research-intelligence/market-intelligence-panel.webp',
    why: 'services/sub/research-intelligence/market-intelligence-why.webp',
    story: 'services/sub/research-intelligence/market-intelligence-story.webp',
    band: 'services/sub/research-intelligence/market-intelligence-band.webp',
    strip: [
      'services/sub/research-intelligence/market-intelligence-strip-1.webp',
      'services/sub/research-intelligence/market-intelligence-strip-2.webp',
      'services/sub/research-intelligence/market-intelligence-strip-3.webp',
      'services/sub/research-intelligence/market-intelligence-strip-4.webp',
      'services/sub/research-intelligence/market-intelligence-strip-5.webp',
      'services/sub/research-intelligence/market-intelligence-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/market-intelligence-talk.webp',
  },
  'research-intelligence/research-reports': {
    hero: 'services/sub/research-intelligence/research-reports-hero.webp',
    panel: 'services/sub/research-intelligence/research-reports-panel.webp',
    why: 'services/sub/research-intelligence/research-reports-why.webp',
    story: 'services/sub/research-intelligence/research-reports-story.webp',
    band: 'services/sub/research-intelligence/research-reports-band.webp',
    strip: [
      'services/sub/research-intelligence/research-reports-strip-1.webp',
      'services/sub/research-intelligence/research-reports-strip-2.webp',
      'services/sub/research-intelligence/research-reports-strip-3.webp',
      'services/sub/research-intelligence/research-reports-strip-4.webp',
      'services/sub/research-intelligence/research-reports-strip-5.webp',
      'services/sub/research-intelligence/research-reports-strip-6.webp',
    ],
    talk: 'services/sub/research-intelligence/research-reports-talk.webp',
  },
  'technology-data-ai/technology-consulting': {
    hero: 'services/sub/technology-data-ai/technology-consulting-hero.webp',
    panel: 'services/sub/technology-data-ai/technology-consulting-panel.webp',
    why: 'services/sub/technology-data-ai/technology-consulting-why.webp',
    story: 'services/sub/technology-data-ai/technology-consulting-story.webp',
    band: 'services/sub/technology-data-ai/technology-consulting-band.webp',
    strip: [
      'services/sub/technology-data-ai/technology-consulting-strip-1.webp',
      'services/sub/technology-data-ai/technology-consulting-strip-2.webp',
      'services/sub/technology-data-ai/technology-consulting-strip-3.webp',
      'services/sub/technology-data-ai/technology-consulting-strip-4.webp',
      'services/sub/technology-data-ai/technology-consulting-strip-5.webp',
      'services/sub/technology-data-ai/technology-consulting-strip-6.webp',
    ],
    talk: 'services/sub/technology-data-ai/technology-consulting-talk.webp',
  },
  'technology-data-ai/ai-solutions': {
    hero: 'services/sub/technology-data-ai/ai-solutions-hero.webp',
    panel: 'services/sub/technology-data-ai/ai-solutions-panel.webp',
    why: 'services/sub/technology-data-ai/ai-solutions-why.webp',
    story: 'services/sub/technology-data-ai/ai-solutions-story.webp',
    band: 'services/sub/technology-data-ai/ai-solutions-band.webp',
    strip: [
      'services/sub/technology-data-ai/ai-solutions-strip-1.webp',
      'services/sub/technology-data-ai/ai-solutions-strip-2.webp',
      'services/sub/technology-data-ai/ai-solutions-strip-3.webp',
      'services/sub/technology-data-ai/ai-solutions-strip-4.webp',
      'services/sub/technology-data-ai/ai-solutions-strip-5.webp',
      'services/sub/technology-data-ai/ai-solutions-strip-6.webp',
    ],
    talk: 'services/sub/technology-data-ai/ai-solutions-talk.webp',
  },
  'technology-data-ai/erp-dashboards': {
    hero: 'services/sub/technology-data-ai/erp-dashboards-hero.webp',
    panel: 'services/sub/technology-data-ai/erp-dashboards-panel.webp',
    why: 'services/sub/technology-data-ai/erp-dashboards-why.webp',
    story: 'services/sub/technology-data-ai/erp-dashboards-story.webp',
    band: 'services/sub/technology-data-ai/erp-dashboards-band.webp',
    strip: [
      'services/sub/technology-data-ai/erp-dashboards-strip-1.webp',
      'services/sub/technology-data-ai/erp-dashboards-strip-2.webp',
      'services/sub/technology-data-ai/erp-dashboards-strip-3.webp',
      'services/sub/technology-data-ai/erp-dashboards-strip-4.webp',
      'services/sub/technology-data-ai/erp-dashboards-strip-5.webp',
      'services/sub/technology-data-ai/erp-dashboards-strip-6.webp',
    ],
    talk: 'services/sub/technology-data-ai/erp-dashboards-talk.webp',
  },
  'technology-data-ai/proptech': {
    hero: 'services/sub/technology-data-ai/proptech-hero.webp',
    panel: 'services/sub/technology-data-ai/proptech-panel.webp',
    why: 'services/sub/technology-data-ai/proptech-why.webp',
    story: 'services/sub/technology-data-ai/proptech-story.webp',
    band: 'services/sub/technology-data-ai/proptech-band.webp',
    strip: [
      'services/sub/technology-data-ai/proptech-strip-1.webp',
      'services/sub/technology-data-ai/proptech-strip-2.webp',
      'services/sub/technology-data-ai/proptech-strip-3.webp',
      'services/sub/technology-data-ai/proptech-strip-4.webp',
      'services/sub/technology-data-ai/proptech-strip-5.webp',
      'services/sub/technology-data-ai/proptech-strip-6.webp',
    ],
    talk: 'services/sub/technology-data-ai/proptech-talk.webp',
  },
  'technology-data-ai/enterprise-solutions': {
    hero: 'services/sub/technology-data-ai/enterprise-solutions-hero.webp',
    panel: 'services/sub/technology-data-ai/enterprise-solutions-panel.webp',
    why: 'services/sub/technology-data-ai/enterprise-solutions-why.webp',
    story: 'services/sub/technology-data-ai/enterprise-solutions-story.webp',
    band: 'services/sub/technology-data-ai/enterprise-solutions-band.webp',
    strip: [
      'services/sub/technology-data-ai/enterprise-solutions-strip-1.webp',
      'services/sub/technology-data-ai/enterprise-solutions-strip-2.webp',
      'services/sub/technology-data-ai/enterprise-solutions-strip-3.webp',
      'services/sub/technology-data-ai/enterprise-solutions-strip-4.webp',
      'services/sub/technology-data-ai/enterprise-solutions-strip-5.webp',
      'services/sub/technology-data-ai/enterprise-solutions-strip-6.webp',
    ],
    talk: 'services/sub/technology-data-ai/enterprise-solutions-talk.webp',
  },
};
