/**
 * Every table-backed admin screen, declared from the imported schema.
 *
 * Each entry below is a table of the www.valunxt.com database (schema.ts) and
 * what the panel lets an administrator do with it. Which tables have a screen,
 * and whether it can create, edit or delete, follows from what the table holds:
 *
 *   records an editor maintains     authors, redirects, keywords, accounts, and
 *                                   the client portal's clients and their
 *                                   contacts, deadlines, requests, documents,
 *                                   ledger and messages — full CRUD
 *   logs a system wrote             security events, malware scans, file
 *                                   hashes, SEO audits, PageSpeed runs, sitemap
 *                                   runs, portal activity, sign-in attempts —
 *                                   read-only, deletable where clearing is useful
 *   internal state                  pa_tokens (password-reset hashes),
 *                                   pa_thread_reads (read receipts),
 *                                   vx_geo_cache (IP lookups) — no screen of
 *                                   their own; shown where they are used
 *
 * Posts, leads, page SEO, analytics and the dashboard have screens of their own.
 */
import type { FieldDef, ResourceDef } from './resource-types';

const DOC_CATEGORIES = ['Bank Statement', 'Invoice', 'Contract', 'Payroll', 'Tax Return', 'Other'].map(
  (v) => [v, v] as const
);

const CLIENT = { table: 'pa_clients', key: 'id', label: "COALESCE(NULLIF(trade_name, ''), legal_name)", order: 'legal_name' };
const PORTAL_USER = { table: 'pa_users', key: 'id', label: "CONCAT(full_name, ' <', email, '>')", order: 'full_name' };
const STAFF = {
  table: 'pa_users',
  key: 'id',
  label: "CONCAT(full_name, ' (', REPLACE(role, '_', ' '), ')')",
  order: 'full_name',
  where: "role IN ('firm_admin', 'accountant')",
};
const DOCUMENT = { table: 'pa_documents', key: 'id', label: 'file_name', order: 'created_at DESC' };

const clientField: FieldDef = {
  name: 'client_id',
  label: 'Client',
  type: 'relation',
  relation: CLIENT,
  required: true,
  list: true,
  filter: true,
};

export const RESOURCES: ResourceDef[] = [
  /* ---- Content ----------------------------------------------------------- */
  {
    key: 'authors',
    table: 'vx_authors',
    pk: 'id',
    numericPk: true,
    label: 'Authors',
    singular: 'Author',
    description: 'The bylines articles are published under. A profile’s name, role and photo appear in the article sidebar.',
    icon: 'user',
    group: 'Content',
    titleField: 'name',
    orderBy: 'name ASC',
    create: true,
    edit: true,
    remove: true,
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, max: 120, list: true, search: true },
      {
        name: 'slug',
        label: 'Slug',
        type: 'text',
        max: 140,
        unique: true,
        list: true,
        search: true,
        display: 'mono',
        help: 'Letters, numbers and hyphens. Left blank, it is made from the name.',
      },
      { name: 'title', label: 'Role', type: 'text', max: 160, nullable: true, list: true, placeholder: 'Corporate Tax Lead', help: 'Shown under the name in the article byline.' },
      { name: 'email', label: 'Email', type: 'email', max: 190, nullable: true, search: true },
      { name: 'linkedin', label: 'LinkedIn URL', type: 'url', max: 255, nullable: true },
      { name: 'avatar', label: 'Photo', type: 'path', max: 255, nullable: true, placeholder: '/assets/content/uploads/team/name.webp', help: 'A site path or full URL. Shown in the byline in place of the initial.' },
      { name: 'bio', label: 'Bio', type: 'textarea', nullable: true, full: true },
      { name: 'created_at', label: 'Created', type: 'datetime', readOnly: true, list: true, display: 'date' },
    ],
  },

  /* ---- SEO ----------------------------------------------------------------- */
  {
    key: 'redirects',
    table: 'vx_redirects',
    pk: 'id',
    numericPk: true,
    label: 'Redirects',
    singular: 'Redirect',
    description:
      'Addresses that forward to another page. Active rules apply to the live site within fifteen seconds — including every address of the previous www.valunxt.com site.',
    icon: 'arrowRight',
    group: 'SEO',
    titleField: 'from_path',
    orderBy: 'from_path ASC',
    create: true,
    edit: true,
    remove: true,
    perPage: 50,
    fields: [
      {
        name: 'from_path',
        label: 'From path',
        type: 'text',
        required: true,
        max: 255,
        unique: true,
        list: true,
        search: true,
        display: 'mono',
        placeholder: '/services/old-page',
        help: 'The address to catch, from the site root. A trailing slash and “.html” are ignored when matching.',
      },
      {
        name: 'to_url',
        label: 'To',
        type: 'text',
        required: true,
        max: 255,
        list: true,
        search: true,
        display: 'mono',
        placeholder: '/en-ae/services/new-page/',
        help: 'A site path (/en-ae/…) or a full https:// URL.',
      },
      {
        name: 'code',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          ['301', '301 — Moved permanently'],
          ['302', '302 — Found (temporary)'],
          ['307', '307 — Temporary, keep method'],
          ['308', '308 — Permanent, keep method'],
        ],
        defaultValue: '301',
        list: true,
        filter: true,
        display: 'pill',
      },
      { name: 'active', label: 'Active', type: 'checkbox', defaultValue: '1', list: true, filter: true, display: 'bool' },
      { name: 'note', label: 'Note', type: 'text', max: 190, nullable: true, list: true, search: true, full: true },
      { name: 'created_at', label: 'Created', type: 'datetime', readOnly: true, display: 'date' },
    ],
  },
  {
    key: 'keywords',
    table: 'vx_keywords',
    pk: 'id',
    numericPk: true,
    label: 'Keywords',
    singular: 'Keyword',
    description: 'Search terms the site is tracked for, with the page meant to rank for each.',
    icon: 'search',
    group: 'SEO',
    titleField: 'keyword',
    orderBy: 'keyword ASC',
    create: true,
    edit: true,
    remove: true,
    fields: [
      { name: 'keyword', label: 'Keyword', type: 'text', required: true, max: 190, unique: true, list: true, search: true },
      { name: 'target_page', label: 'Target page', type: 'text', max: 255, nullable: true, list: true, search: true, display: 'mono', placeholder: '/en-ae/services/accounting-tax-services/' },
      { name: 'found_on', label: 'Pages using it', type: 'int', readOnly: true, list: true },
      { name: 'in_titles', label: 'In titles', type: 'int', readOnly: true, list: true },
      { name: 'last_checked', label: 'Last checked', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
    ],
  },
  {
    key: 'seo-audits',
    table: 'vx_seo_audits',
    pk: 'id',
    numericPk: true,
    label: 'SEO Audits',
    singular: 'SEO audit',
    description: 'Site-wide SEO audits run by the previous panel: pages checked, the score, and every issue found.',
    icon: 'checkCircle',
    group: 'SEO',
    titleField: 'ts',
    orderBy: 'ts DESC, id DESC',
    remove: true,
    edit: true,
    fields: [
      { name: 'ts', label: 'Run at', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'pages', label: 'Pages', type: 'int', readOnly: true, list: true },
      { name: 'score', label: 'Score', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'report', label: 'Report', type: 'json', readOnly: true, full: true, display: 'excerpt' },
    ],
  },

  /* ---- Insights ------------------------------------------------------------ */
  {
    key: 'performance',
    table: 'vx_psi',
    pk: 'id',
    numericPk: true,
    label: 'Performance',
    singular: 'PageSpeed run',
    description: 'Google PageSpeed Insights results: the four scores and the Core Web Vitals, per URL and device.',
    icon: 'trendUp',
    group: 'Insights',
    titleField: 'url',
    orderBy: 'ts DESC, id DESC',
    remove: true,
    edit: true,
    fields: [
      { name: 'ts', label: 'Run at', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'url', label: 'URL', type: 'text', readOnly: true, list: true, search: true, display: 'mono' },
      { name: 'strategy', label: 'Device', type: 'text', readOnly: true, list: true, filter: true, options: [['mobile', 'Mobile'], ['desktop', 'Desktop']] },
      { name: 'performance', label: 'Performance', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'seo', label: 'SEO', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'accessibility', label: 'Accessibility', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'best_practices', label: 'Best practices', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'lcp_ms', label: 'LCP (ms)', type: 'int', readOnly: true },
      { name: 'cls', label: 'CLS (×1000)', type: 'int', readOnly: true },
      { name: 'inp_ms', label: 'INP (ms)', type: 'int', readOnly: true },
      { name: 'fcp_ms', label: 'FCP (ms)', type: 'int', readOnly: true },
      { name: 'tbt_ms', label: 'TBT (ms)', type: 'int', readOnly: true },
    ],
  },

  /* ---- Client portal -------------------------------------------------------- */
  {
    key: 'clients',
    table: 'pa_clients',
    pk: 'id',
    numericPk: true,
    label: 'Clients',
    singular: 'Client',
    description: 'Companies on the client portal: their licence, VAT and Corporate Tax registration, engagement tier and onboarding.',
    icon: 'users',
    group: 'Client Portal',
    titleField: 'legal_name',
    orderBy: 'legal_name ASC',
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    fields: [
      { name: 'legal_name', label: 'Legal name', type: 'text', required: true, max: 190, list: true, search: true },
      { name: 'trade_name', label: 'Trade name', type: 'text', max: 190, nullable: true, list: true, search: true },
      {
        name: 'entity_type',
        label: 'Entity type',
        type: 'select',
        required: true,
        options: [['Mainland', 'Mainland'], ['Free Zone', 'Free Zone'], ['Offshore', 'Offshore']],
        defaultValue: 'Mainland',
        list: true,
        filter: true,
      },
      { name: 'free_zone_name', label: 'Free zone', type: 'text', max: 190, nullable: true, placeholder: 'DMCC' },
      { name: 'trade_licence_no', label: 'Trade licence no.', type: 'text', max: 100, nullable: true, search: true, display: 'mono' },
      { name: 'licence_issue_date', label: 'Licence issued', type: 'date', nullable: true },
      { name: 'licence_expiry_date', label: 'Licence expires', type: 'date', nullable: true, list: true, display: 'date' },
      { name: 'incorporation_date', label: 'Incorporated', type: 'date', nullable: true },
      { name: 'financial_year_end', label: 'Financial year end', type: 'text', max: 20, nullable: true, placeholder: '31 December' },
      { name: 'vat_trn', label: 'VAT TRN', type: 'text', max: 30, nullable: true, search: true, display: 'mono' },
      { name: 'vat_cycle', label: 'VAT cycle', type: 'select', nullable: true, options: [['Monthly', 'Monthly'], ['Quarterly', 'Quarterly']] },
      { name: 'ct_reg_no', label: 'CT registration no.', type: 'text', max: 30, nullable: true, display: 'mono' },
      { name: 'ct_status', label: 'CT status', type: 'text', max: 60, nullable: true },
      { name: 'qfzp', label: 'Qualifying Free Zone Person', type: 'checkbox', defaultValue: '0' },
      { name: 'first_ct_period_start', label: 'First CT period start', type: 'date', nullable: true },
      { name: 'first_ct_period_end', label: 'First CT period end', type: 'date', nullable: true },
      {
        name: 'tier',
        label: 'Tier',
        type: 'select',
        required: true,
        options: [['Starter', 'Starter'], ['Growth', 'Growth'], ['CFO', 'CFO']],
        defaultValue: 'Starter',
        list: true,
        filter: true,
        display: 'pill',
      },
      { name: 'monthly_fee', label: 'Monthly fee (AED)', type: 'decimal', min: 0, max: 99999999, defaultValue: '0.00', list: true, display: 'money' },
      { name: 'assigned_accountant_id', label: 'Assigned accountant', type: 'relation', relation: STAFF, nullable: true },
      {
        name: 'onboarding_status',
        label: 'Onboarding',
        type: 'select',
        required: true,
        options: [
          ['Invited', 'Invited'],
          ['Details pending', 'Details pending'],
          ['Documents pending', 'Documents pending'],
          ['Active', 'Active'],
        ],
        defaultValue: 'Invited',
        list: true,
        filter: true,
        display: 'pill',
      },
      { name: 'engagement_start', label: 'Engagement start', type: 'date', nullable: true },
      { name: 'notes', label: 'Notes', type: 'textarea', nullable: true, full: true },
    ],
  },
  {
    key: 'client-contacts',
    table: 'pa_client_contacts',
    pk: 'id',
    numericPk: true,
    label: 'Client Contacts',
    singular: 'Contact',
    description: 'The people at each client company.',
    icon: 'user',
    group: 'Client Portal',
    navHidden: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    titleField: 'name',
    orderBy: 'is_primary DESC, name ASC',
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    fields: [
      clientField,
      { name: 'name', label: 'Name', type: 'text', required: true, max: 190, list: true, search: true },
      { name: 'email', label: 'Email', type: 'email', max: 190, nullable: true, list: true, search: true },
      { name: 'phone', label: 'Phone', type: 'tel', max: 40, nullable: true, list: true },
      { name: 'role_label', label: 'Role', type: 'text', max: 100, nullable: true, list: true, placeholder: 'Finance manager' },
      { name: 'is_primary', label: 'Primary contact', type: 'checkbox', defaultValue: '0', list: true, display: 'bool' },
    ],
  },
  {
    key: 'deadlines',
    table: 'pa_deadlines',
    pk: 'id',
    numericPk: true,
    label: 'Deadlines',
    singular: 'Deadline',
    description: 'Filing and renewal deadlines tracked for each client: VAT returns, Corporate Tax returns, licence renewals.',
    icon: 'calendar',
    group: 'Client Portal',
    titleField: 'type',
    orderBy: "status = 'filed' ASC, due_date ASC",
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    fields: [
      clientField,
      { name: 'type', label: 'Type', type: 'text', required: true, max: 80, list: true, search: true, placeholder: 'VAT Return' },
      { name: 'period', label: 'Period', type: 'text', max: 60, nullable: true, list: true, placeholder: 'Q3 2026' },
      { name: 'due_date', label: 'Due', type: 'date', required: true, list: true, display: 'date' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: [['pending', 'Pending'], ['filed', 'Filed']], defaultValue: 'pending', list: true, filter: true, display: 'pill' },
      { name: 'penalty_note', label: 'Penalty note', type: 'text', max: 255, nullable: true, full: true, placeholder: 'AED 1,000 late-filing penalty' },
    ],
  },
  {
    key: 'document-requests',
    table: 'pa_document_requests',
    pk: 'id',
    numericPk: true,
    label: 'Document Requests',
    singular: 'Document request',
    description: 'Documents asked of a client, and the upload that fulfilled each request.',
    icon: 'file',
    group: 'Client Portal',
    navHidden: true,
    titleField: 'title',
    orderBy: "status = 'Open' DESC, due_date IS NULL, due_date ASC",
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    fields: [
      clientField,
      { name: 'title', label: 'Title', type: 'text', required: true, max: 190, list: true, search: true },
      { name: 'category', label: 'Category', type: 'select', required: true, options: DOC_CATEGORIES, defaultValue: 'Other', list: true, filter: true },
      { name: 'period', label: 'Period', type: 'text', max: 60, nullable: true, list: true },
      { name: 'due_date', label: 'Due', type: 'date', nullable: true, list: true, display: 'date' },
      { name: 'status', label: 'Status', type: 'select', required: true, options: [['Open', 'Open'], ['Fulfilled', 'Fulfilled'], ['Cancelled', 'Cancelled']], defaultValue: 'Open', list: true, filter: true, display: 'pill' },
      { name: 'fulfilled_document_id', label: 'Fulfilled by', type: 'relation', relation: DOCUMENT, nullable: true },
      { name: 'created_by', label: 'Requested by', type: 'relation', relation: STAFF, nullable: true },
      { name: 'note', label: 'Note', type: 'text', max: 500, nullable: true, full: true },
    ],
  },
  {
    key: 'documents',
    table: 'pa_documents',
    pk: 'id',
    numericPk: true,
    label: 'Documents',
    singular: 'Document',
    description:
      'Files clients and accountants exchanged through the portal. The records came with the database; the files themselves were stored on the previous server.',
    icon: 'file',
    group: 'Client Portal',
    navHidden: true,
    titleField: 'file_name',
    orderBy: 'created_at DESC, id DESC',
    edit: true,
    remove: true,
    adminOnly: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    fields: [
      clientField,
      { name: 'file_name', label: 'File name', type: 'text', required: true, max: 255, list: true, search: true },
      { name: 'stored_name', label: 'Stored as', type: 'text', readOnly: true, display: 'mono' },
      { name: 'category', label: 'Category', type: 'select', required: true, options: DOC_CATEGORIES, list: true, filter: true },
      { name: 'period', label: 'Period', type: 'text', max: 60, nullable: true, list: true },
      { name: 'status', label: 'Status', type: 'select', required: true, options: [['Requested', 'Requested'], ['Uploaded', 'Uploaded'], ['Reviewed', 'Reviewed'], ['Shared', 'Shared']], list: true, filter: true, display: 'pill' },
      { name: 'shared_with_client', label: 'Shared with client', type: 'checkbox', list: true, display: 'bool' },
      { name: 'uploaded_by', label: 'Uploaded by', type: 'relation', relation: PORTAL_USER, nullable: true },
      { name: 'size_bytes', label: 'Size', type: 'int', readOnly: true, list: true, display: 'bytes' },
      { name: 'created_at', label: 'Uploaded', type: 'datetime', readOnly: true, list: true, display: 'date' },
    ],
  },
  {
    key: 'ledger',
    table: 'pa_ledger_entries',
    pk: 'id',
    numericPk: true,
    label: 'Ledger Entries',
    singular: 'Ledger entry',
    description: 'Bookkeeping entries kept for each client: revenue, expenses, payroll and VAT.',
    icon: 'chart',
    group: 'Client Portal',
    navHidden: true,
    titleField: 'description',
    orderBy: 'entry_date DESC, id DESC',
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    perPage: 50,
    fields: [
      clientField,
      { name: 'entry_date', label: 'Date', type: 'date', required: true, list: true, display: 'date' },
      { name: 'description', label: 'Description', type: 'text', required: true, max: 255, list: true, search: true, full: true },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        required: true,
        options: ['Revenue', 'Expense', 'VAT Input', 'VAT Output', 'Payroll', 'Other'].map((v) => [v, v] as const),
        defaultValue: 'Other',
        list: true,
        filter: true,
      },
      { name: 'debit', label: 'Debit (AED)', type: 'decimal', min: 0, max: 9999999999, defaultValue: '0.00', list: true, display: 'money' },
      { name: 'credit', label: 'Credit (AED)', type: 'decimal', min: 0, max: 9999999999, defaultValue: '0.00', list: true, display: 'money' },
      { name: 'vat_amount', label: 'VAT (AED)', type: 'decimal', min: 0, max: 9999999999, defaultValue: '0.00', list: true, display: 'money' },
      { name: 'document_id', label: 'Supporting document', type: 'relation', relation: DOCUMENT, nullable: true },
      { name: 'created_by', label: 'Entered by', type: 'relation', relation: STAFF, nullable: true },
      { name: 'notes', label: 'Notes', type: 'text', max: 500, nullable: true, full: true },
    ],
  },
  {
    key: 'messages',
    table: 'pa_messages',
    pk: 'id',
    numericPk: true,
    label: 'Messages',
    singular: 'Message',
    description: 'The message thread between each client and the firm.',
    icon: 'message',
    group: 'Client Portal',
    navHidden: true,
    titleField: 'body',
    orderBy: 'created_at DESC, id DESC',
    create: true,
    remove: true,
    edit: true,
    adminOnly: true,
    parent: { field: 'client_id', resource: 'clients', label: 'Client' },
    fields: [
      clientField,
      { name: 'sender_id', label: 'From', type: 'relation', relation: PORTAL_USER, required: true, list: true },
      { name: 'body', label: 'Message', type: 'textarea', required: true, list: true, search: true, full: true, display: 'excerpt' },
      { name: 'attachment_name', label: 'Attachment', type: 'text', readOnly: true, list: true },
      { name: 'created_at', label: 'Sent', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
    ],
  },
  {
    key: 'portal-users',
    table: 'pa_users',
    pk: 'id',
    numericPk: true,
    label: 'Portal Users',
    singular: 'Portal user',
    description: 'Who can sign in to the client portal: the firm’s administrators and accountants, and each client’s own users.',
    icon: 'users',
    group: 'Client Portal',
    titleField: 'full_name',
    orderBy: "FIELD(role, 'firm_admin', 'accountant', 'client'), full_name ASC",
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    fields: [
      { name: 'full_name', label: 'Full name', type: 'text', required: true, max: 190, list: true, search: true },
      { name: 'email', label: 'Email', type: 'email', required: true, max: 190, unique: true, list: true, search: true },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: [['firm_admin', 'Firm admin'], ['accountant', 'Accountant'], ['client', 'Client']],
        defaultValue: 'client',
        list: true,
        filter: true,
        display: 'pill',
      },
      { name: 'client_id', label: 'Client', type: 'relation', relation: CLIENT, nullable: true, list: true, filter: true, help: 'Required for a client user; leave empty for firm staff.' },
      { name: 'phone', label: 'Phone', type: 'tel', max: 40, nullable: true },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [['invited', 'Invited'], ['active', 'Active'], ['disabled', 'Disabled']],
        defaultValue: 'invited',
        list: true,
        filter: true,
        display: 'pill',
      },
      {
        name: 'password_hash',
        label: 'Password',
        type: 'password',
        nullable: true,
        help: 'Leave blank to keep the current password. At least 8 characters.',
      },
      { name: 'created_at', label: 'Created', type: 'datetime', readOnly: true, list: true, display: 'date' },
    ],
  },
  {
    key: 'portal-activity',
    table: 'pa_activity_log',
    pk: 'id',
    numericPk: true,
    label: 'Portal Activity',
    singular: 'Activity entry',
    description: 'What happened on the client portal: sign-ins, messages, document requests, onboarding — and changes made here.',
    icon: 'clock',
    group: 'Client Portal',
    titleField: 'event_type',
    orderBy: 'created_at DESC, id DESC',
    adminOnly: true,
    edit: true,
    perPage: 50,
    fields: [
      { name: 'created_at', label: 'When', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'event_type', label: 'Event', type: 'text', readOnly: true, list: true, filter: true, display: 'pill' },
      { name: 'client_id', label: 'Client', type: 'relation', relation: CLIENT, readOnly: true, list: true, filter: true },
      { name: 'actor_id', label: 'By', type: 'relation', relation: PORTAL_USER, readOnly: true, list: true },
      { name: 'detail', label: 'Detail', type: 'text', readOnly: true, list: true, search: true, full: true },
    ],
  },

  /* ---- System --------------------------------------------------------------- */
  {
    key: 'admin-users',
    table: 'vx_users',
    pk: 'id',
    numericPk: true,
    label: 'Admin Users',
    singular: 'Administrator',
    description: 'Who can sign in to this panel. Administrators manage everything; editors manage content, SEO and leads.',
    icon: 'shield',
    group: 'System',
    titleField: 'name',
    orderBy: 'name ASC',
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, max: 120, list: true, search: true },
      { name: 'email', label: 'Email', type: 'email', required: true, max: 190, unique: true, list: true, search: true },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: [['admin', 'Administrator'], ['editor', 'Editor']],
        defaultValue: 'editor',
        list: true,
        filter: true,
        display: 'pill',
      },
      { name: 'pass_hash', label: 'Password', type: 'password', help: 'At least 8 characters. On an existing account, leave blank to keep the current password.' },
      { name: 'last_login', label: 'Last sign-in', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'created_at', label: 'Created', type: 'datetime', readOnly: true, display: 'date' },
    ],
  },
  {
    key: 'security-events',
    table: 'vx_security_events',
    pk: 'id',
    numericPk: true,
    label: 'Security Log',
    singular: 'Security event',
    description: 'Failed and blocked sign-ins, and bot submissions caught by the form honeypot.',
    icon: 'alertCircle',
    group: 'System',
    navHidden: true,
    titleField: 'type',
    orderBy: 'ts DESC, id DESC',
    remove: true,
    edit: true,
    adminOnly: true,
    perPage: 50,
    fields: [
      { name: 'ts', label: 'When', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'type', label: 'Type', type: 'text', readOnly: true, list: true, filter: true, display: 'pill' },
      { name: 'ip', label: 'IP address', type: 'text', readOnly: true, list: true, search: true, display: 'mono' },
      { name: 'detail', label: 'Detail', type: 'text', readOnly: true, list: true, search: true },
      { name: 'path', label: 'Path', type: 'text', readOnly: true, list: true, display: 'mono' },
      { name: 'ua', label: 'User agent', type: 'text', readOnly: true, full: true },
    ],
  },
  {
    key: 'scans',
    table: 'vx_scans',
    pk: 'id',
    numericPk: true,
    label: 'Malware Scans',
    singular: 'Scan',
    description: 'File-integrity and malware scans the previous panel ran over its PHP files.',
    icon: 'shield',
    group: 'System',
    navHidden: true,
    titleField: 'ts',
    orderBy: 'ts DESC, id DESC',
    remove: true,
    edit: true,
    adminOnly: true,
    fields: [
      { name: 'ts', label: 'Run at', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'kind', label: 'Kind', type: 'text', readOnly: true, list: true, display: 'pill' },
      { name: 'files_scanned', label: 'Files scanned', type: 'int', readOnly: true, list: true },
      { name: 'issues_found', label: 'Issues', type: 'int', readOnly: true, list: true, display: 'pill' },
      { name: 'report', label: 'Report', type: 'json', readOnly: true, full: true, display: 'excerpt' },
    ],
  },
  {
    key: 'file-hashes',
    table: 'vx_file_hashes',
    pk: 'path',
    numericPk: false,
    label: 'File Hashes',
    singular: 'File hash',
    description: 'The integrity baseline of the previous panel’s PHP files: SHA-256 and size of each, as last seen.',
    icon: 'key',
    group: 'System',
    navHidden: true,
    titleField: 'path',
    orderBy: 'path ASC',
    edit: true,
    adminOnly: true,
    perPage: 50,
    fields: [
      { name: 'path', label: 'Path', type: 'text', readOnly: true, list: true, search: true, display: 'mono' },
      { name: 'hash', label: 'SHA-256', type: 'text', readOnly: true, list: true, display: 'mono' },
      { name: 'size', label: 'Size', type: 'int', readOnly: true, list: true, display: 'bytes' },
      { name: 'seen', label: 'Seen', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
    ],
  },
  {
    key: 'login-attempts',
    table: 'pa_login_attempts',
    pk: 'id',
    numericPk: true,
    label: 'Portal Sign-in Attempts',
    singular: 'Sign-in attempt',
    description: 'Failed client-portal sign-ins, the portal’s own rate-limit record.',
    icon: 'lock',
    group: 'System',
    navHidden: true,
    titleField: 'email',
    orderBy: 'attempted_at DESC, id DESC',
    remove: true,
    edit: true,
    adminOnly: true,
    fields: [
      { name: 'attempted_at', label: 'When', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'email', label: 'Email', type: 'text', readOnly: true, list: true, search: true },
      { name: 'ip', label: 'IP address', type: 'text', readOnly: true, list: true, search: true, display: 'mono' },
    ],
  },
  {
    key: 'sitemap-runs',
    table: 'vx_sitemap_runs',
    pk: 'id',
    numericPk: true,
    label: 'Sitemap Runs',
    singular: 'Sitemap run',
    description: 'Every sitemap generation: how many URLs it listed, and how many were added, removed or changed since the one before.',
    icon: 'globe',
    group: 'SEO',
    navHidden: true,
    titleField: 'ts',
    orderBy: 'ts DESC, id DESC',
    edit: true,
    perPage: 50,
    fields: [
      { name: 'ts', label: 'Run at', type: 'datetime', readOnly: true, list: true, display: 'datetime' },
      { name: 'status', label: 'Status', type: 'text', readOnly: true, list: true, filter: true, display: 'pill' },
      { name: 'total_urls', label: 'URLs', type: 'int', readOnly: true, list: true },
      { name: 'added', label: 'Added', type: 'int', readOnly: true, list: true },
      { name: 'removed', label: 'Removed', type: 'int', readOnly: true, list: true },
      { name: 'modified', label: 'Modified', type: 'int', readOnly: true, list: true },
      { name: 'duration_ms', label: 'Took (ms)', type: 'int', readOnly: true, list: true },
      { name: 'error', label: 'Error', type: 'text', readOnly: true, full: true },
    ],
  },
  {
    key: 'site-settings',
    table: 'vx_settings',
    pk: 'k',
    numericPk: false,
    label: 'Site Settings',
    singular: 'Setting',
    description:
      'The key/value store the panel keeps its own state in: the site URL, sitemap stamps and sync fingerprints. Change these only if you know what reads them.',
    icon: 'settings',
    group: 'System',
    navHidden: true,
    titleField: 'k',
    orderBy: 'k ASC',
    create: true,
    edit: true,
    remove: true,
    adminOnly: true,
    fields: [
      { name: 'k', label: 'Key', type: 'text', required: true, max: 80, unique: true, list: true, search: true, display: 'mono', createOnly: true },
      { name: 'v', label: 'Value', type: 'textarea', nullable: true, list: true, search: true, full: true, display: 'excerpt' },
    ],
  },
];

const BY_KEY = new Map(RESOURCES.map((r) => [r.key, r]));

/** The resource behind a URL segment, or undefined. */
export function resourceByKey(key: string): ResourceDef | undefined {
  return BY_KEY.get(String(key));
}

/** A field of a resource, by column. */
export function resourceField(def: ResourceDef, name: string): FieldDef | undefined {
  return def.fields.find((f) => f.name === name);
}

/** The sidebar item a screen sits under: its own, or the section that links to it. */
export function navKeyFor(def: ResourceDef): string {
  if (!def.navHidden) return def.key;
  if (def.parent) return def.parent.resource;
  if (['security-events', 'scans', 'file-hashes', 'login-attempts'].includes(def.key)) return 'security';
  if (def.key === 'sitemap-runs') return 'sitemap';
  if (def.key === 'site-settings') return 'settings';
  return 'none';
}

/** The resources listed on a parent's detail page (a client's contacts, deadlines…). */
export function childResources(parentKey: string): ResourceDef[] {
  return RESOURCES.filter((r) => r.parent?.resource === parentKey);
}
